FROM public.ecr.aws/lambda/python:3.12

RUN pip install numpy -t /opt/python
RUN pip install opensearch-py -t /opt/python
RUN pip install requests-aws4auth -t /opt/python
RUN pip install aws-requests-auth -t /opt/python
RUN pip install requests_toolbelt -t /opt/python
